### ISSUE TITLE
alphafold reference data

### ISSUE THREAD

**Issue by bernt-matthias** [idiv-biodiversity/scddl#8]
Reference data needed for `alphafold` can be downloaded with 

```
/software/easybuild-broadwell/software/AlphaFold/2.2.2-fosscuda-2020b-TensorFlow-2.5.0/scripts/download_all_data.sh DIR
```

we would like to have this in `/data/db/`

I'm pretty sure that we won't get checksums for the files that are downloaded from various sources. 

Should we still manage this via scdll @wookietreiber ? Or are there other means? 

We would still need versioning (alphafold version + date).

**Comment by wookietreiber** [comment]
Having no checksums is sad but fine as far as scddl is concerned. The goal is to verify checksums if they are available. You can always pressure the data providers to include checksums :wink:  

Let me know when `aria2c` is ready.

**Comment by bernt-matthias** [comment]
Hi @wookietreiber `aria2/1.36.0` is now available on EVE. How would you like to proceed?

**Comment by DirectorSloan** [comment]
Aria2 no available in broadwell: `ml GCCcore/10.2.0 aria2`

**Comment by wookietreiber** [comment]
> `aria2/1.36.0` is now available on EVE. How would you like to proceed?

Thinking about this, since there aren't any checksums and they have their own scripts, I don't really see a point right now in duplicating the scripting effort for likely no benefit, i.e. we would just make it to have it conform to the existing scddl tooling.

I guess I'll start it manually with the download all script and see how this goes.

**Comment by bernt-matthias** [comment]
Fine with me. 

I'm not sure if reference data depends on the alphafold verison. To be on the safe side I would suggest to download in a folder `$ALPHAFOLD_VERSION/$DOWNLOAD_DATE`. And maybe add `latest` link(s) to all (?) levels?

**Comment by wookietreiber** [comment]
> I'm not sure if reference data depends on the alphafold verison. To be on the safe side I would suggest to download in a folder `$ALPHAFOLD_VERSION/$DOWNLOAD_DATE`.

From looking at the shell scripts, they only download with `aria2c` and then `gunzip` or `tar x`, so no apparent link to the alphafold version.

**Comment by bernt-matthias** [comment]
> so no apparent link to the alphafold version.

except for indirect link that copes by the data that is actually downloaded

**Comment by bernt-matthias** [comment]
Guess we can close this here.
